# Generated by Django 3.2 on 2021-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=4096)),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('albums', models.CharField(max_length=4096)),
                ('tracks', models.CharField(max_length=4096)),
                ('self', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
