# Generated by Django 3.2 on 2021-04-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_t2', '0002_alter_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='updated_at',
        ),
    ]
