# Generated by Django 3.2 on 2021-04-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_t2', '0004_alter_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='self',
            new_name='self_url',
        ),
    ]
