# Generated by Django 3.2 on 2021-04-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_t2', '0005_rename_self_artist_self_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('tracks', models.CharField(max_length=4096)),
                ('self_url', models.CharField(max_length=4096)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_t2.artist')),
            ],
        ),
    ]
