# Generated by Django 3.2 on 2021-04-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_t2', '0006_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField(default=0)),
                ('self_url', models.CharField(max_length=4096)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_t2.album')),
            ],
        ),
    ]
